// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfusMr1Jy03tZpm6xFhFlxLXRGMPpVdVM',
    appId: '1:1064355861085:android:7f65e3812764b169f873b4',
    messagingSenderId: '1064355861085',
    projectId: 'shqanda-74a3f',
    databaseURL: 'https://shqanda-74a3f-default-rtdb.firebaseio.com',
    storageBucket: 'shqanda-74a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5UGN6zQrzoex01UDj0JaaDHDepJnq8k',
    appId: '1:1064355861085:ios:8fe666f6cc75ca3ef873b4',
    messagingSenderId: '1064355861085',
    projectId: 'shqanda-74a3f',
    databaseURL: 'https://shqanda-74a3f-default-rtdb.firebaseio.com',
    storageBucket: 'shqanda-74a3f.appspot.com',
    androidClientId: '1064355861085-0qab0flb2b0iebacsqoflbemm27g59su.apps.googleusercontent.com',
    iosClientId: '1064355861085-7g701k128i6hrtntoql10k32nqsql1lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shqandaApplication',
  );
}
