Map<String, String> ar = {
    'Login':'تسجيل الدخول',
    'Email':'البريد الالكتروني',
    'Password':'الرقم السري',
    'Create account':'انشاء حساب',
    'Forget Password?':'نسيت الرقم السري؟',
    'Iam Admin':'أنا مشرف',
    'Please Check Your Internet Connection':'الرجاء التحقق من اتصال الانترنت الخاص بك',
    'Wrong Email or Paassword':'بريد إلكتروني أو كلمة مرور خاطئة',
    'Both Fields Are Empty':'كلا الحقلين فارغين',
    'Email Is Empty':'البريد الإلكتروني فارغ',
    'Please Try Vaild Email':'يرجى محاولة البريد الإلكتروني',
    'Password Is Empty':'كلمة المرور فارغة',
    'Password  Is Too Short':'كلمة المرور قصيرة جدا',
    'Password  Is Too Short':'جميع الحقول فارغة',
    'Name Must Be 6':'يجب أن يكون الاسم 6',
    'Phone Number Must Be 11':'يجب أن يكون رقم الهاتف 11',
    'Adress Is Empty':'العنوان فارغ',
    'UserName':'اسم االمستخدم',
    'Phone Number':'رقم الهاتف',
    'Address':'العنوان',
    'Home Page':'الصفحة الرئيسية',
    'logout':'خروج',
    'Add new item':'اضافة عنصر جديد',
    'Item Image':'صورة العنصر',
    'Capture with camera':'صوره بالكاميرا',
    'Select from Gallery':'اختر من المعرض',
    'Cancel':'الغاء',
    'New Product':'منتج جديد',
    'Add':'اضافه',
    'category name':'اسم الفئه',
    'category name in arabic':'اسم الفئه بالعربي',
    'id':'الهويه الشخصيه',
    'please write email and password':'الرجاء كتابة البريد الإلكتروني وكلمة المرور',
    'Admin Panel':'لوحة التحكم',
    'Add Category':'اضافة فئه',
    'Show category':'عرض الفئه',
    'Categories':'الفئات',
    'Add SubCategory':'اضافة فئه فرعيه',
    'subCategory name':'اسم الفئه الفرعيه',
    'subCategory name in arabic':'اسم الفئه الفرعيه بالعربي',
    'amount':'الكميه',
    'product name in english':'اسم المنتج بالانجليزي',
    'product name in arabic':'اسم المنتج بالعربي',
    'Description in English':'الوصف بالانجليزي',
    'shippingInfo':'تفاصيل الشحن',
    'orderNumber':'رقم الطلب',
    'Price':'السعر',
    'update':'تعديل',
    'delete':'حذف',
    'showSubCategories':'عرض الفئات الفرعيه',
    'My Cart':'العربه',
    'My Orders':'طلباتي',
    'Profile':'الملف الشخصي',
    'ContactUs':'تواصل معنا',
    'About':'عنا',
    'showPrpducts':'عرض المنتجات',
    'Cart':'العربه',
    'Details':'التفاصيل',
    'Quantity':'الكميه',
    'Products':'المنتجات',
    'Edit Profile':'تعديل الملف الشخصي',
    'Save Profile':'حفظ الملف الشخصي',
    'Message':'الرساله',
    'Description in arabic':'الوصف بالعربي',
    'Logout':'تسجيل خروج',
    'ADD TO CART':'اضافه الي العربه',
    'Start order':'ابدا الطلب',
    'Total Price:':'السعر الاجمالي:',
    'Order Details':'تفاصيل الطلب',
    'User Name':'اسم العميل',
    'User Address':'عنوان العميل',
    'User Email':'البريد الالكتروني للعميل',
    'Product Price':'سعر المنتج',
    'Phone Number':'رقم الهاتف',
    'product name:':'اسم المنتج:',
    'Quantity:':'الكميه:',
    'Send':'ارسال',
    '1-Discovers products that do not exist.':'1-يكتشف منتجات غير موجودة.',
    'About Shqanda':'حول شقاندا',
    '2-Excellent quality.':'2-جودة ممتازة.',
    '3- A place responsible for the products it consumes.':'3-مكان مسئول عن المنتجات الي بيستهلكها.',
    '4- A place oriented with product quality and history.':'4-مكان موجهه بجودة المنتج وتاريخة.',
    '5- A place where you care about the societal environment, the people who make the products, I mean, because the products are excellent.':'5-مكان ببهتم بالبيئة المجتمعية الناس الي لتصنع المنتجات يعني علشان المنتجات تكون ممتازة.',
    'My Cart':'عربة التسوق الخاصة بي',
    'price:':'السعر',
    'Show Orders':'عرض الطلبات',
    'Show Messages':'عرض الرسائل',
    'Name:':'الاسم',
    'Email:':'البريد الالكتروني',
    'Message:':'الرساله',
    'Welcome Screen':'مرحبا',
    'Login As Admin':'دخول كأدمن',
    'Login As User':'دخول كمستخدم',
    'Login As Delivery Boy':'دخول كدليفري',
    'Welcome to Shekanda':'اهلا بك في شقنده',
    'Sheqanda innovates advanced and distinctive solutions and products':'شقنده تبتكر حلول ومنتجات متطوره ومميزه',
    'The experience with Sheqanda is governed by quality and a proper diet':'التجربه مع شقنده تحكمها الجوده ونظام غذائي سليم',
    'Shqanda':'جليقية',
    'The Italian experience with Luchra':'التجربه الايطاليه مع لوتشرا',
    'luchra':'لوشيرة',
    'Try coffee, pizza and chocolate mixed with Italian culture':'جرب القهوه,البيتزا والشيكولاته ممزوجه بالثقافه الايطاليه',
    'delete from cart':'حذف من العربه',
    'Start Now':'ابدا الان',
    'Have an account?':'تمتلك حساب بالفعل؟',
    'Have not an account?':'لا تمتلك حساب؟',
    "Today's joy lies in products at the door of the house.":"بهجة اليوم تكمن في منتجات عند باب البيت.",
    'Amount for orders':'المبلغ للطلبات',
    'Next':'التالي',
    'Order':'الطلب',
    'Checkout':'الدفع',
    'Current Address':'العنوان الحالي',
    'Current Phone':'رقم الموبايل الحالي',
    'Edit':'تعديل',
    'Description':'الوصف',
    'Amount:':'الحجم:',
    'User':'مستخدم',
    'Workers in Shekanda':'العاملين في النحاة',
    'Payment Way':'طريقة الدفع'
};
