Map<String, String> en = {
   'Login':'Login',
   'Email':'Email',
   'Password':'Password',
   'Create account':'Create account',
   'Forget Password?':'Forget Password?',
   'Iam Admin':'Iam Admin',
   'Please Check Your Internet Connection':'Please Check Your Internet Connection',
   'Wrong Email or Paassword':'Wrong Email or Paassword',
   'Both Fields Are Empty':'Both Fields Are Empty',
   'Email Is Empty':'Email Is Empty',
   'Please Try Vaild Email':'Please Try Vaild Email',
   'Password Is Empty':'Password Is Empty',
   'Password  Is Too Short':'Password  Is Too Short',
   'All Fields Are Empty':'All Fields Are Empty',
   'Name Must Be 6':'Name Must Be 6',
   'Phone Number Must Be 11':'Phone Number Must Be 11',
   'Adress Is Empty':'Adress Is Empty',
   'UserName':'UserName',
   'Phone Number':'Phone Number',
   'Address':'Address',
   'Home Page':'Home Page',
   'logout':'logout',
   'Add new item':'Add new item',
   'Item Image':'Item Image',
   'Capture with camera':'Capture with camera',
   'Select from Gallery':'Select from Gallery',
   'Cancel':'Cancel',
   'New Product':'New Product',
   'Add':'Add',
   'category name':'category name',
   'category name in arabic':'category name in arabic',
   'id':'id',
   'please write email and password':'please write email and password',
   'Admin Panel':'Admin Panel',
   'Add Category':'Add Category',
   'Show category':'Show category',
   'Categories':'Categories',
   'Add SubCategory':'Add SubCategory',
   'subCategory name':'subCategory name',
   'subCategory name in arabic':'subCategory name in arabic',
   'amount':'amount',
   'product name in english':'product name in english',
   'product name in arabic':'product name in arabic',
   'Description in English':'Description in English',
   'shippingInfo':'shippingInfo',
   'orderNumber':'orderNumber',
   'Price':'Price',
   'update':'update',
   'delete':'delete',
   'showSubCategories':'showSubCategories',
   'My Cart':'My Cart',
   'My Orders':'My Orders',
   'Profile':'Profile',
   'ContactUs':'ContactUs',
   'About':'About',
   'showPrpducts':'showPrpducts',
   'Cart':'Cart',
   'Details':'Details',
   'Total price':'Total price',
   'Quantity':'Quantity',
   'Order Details':'Order Details',
   'Products':'Products',
   'Edit Profile':'Edit Profile',
   'Save Profile':'Save Profile',
   'Message':'Message',
   'Description in arabic':'Description in arabic',
   'Logout':'Logout',
   'ADD TO CART':'ADD TO CART',
   'Start order':'Start order',
   'User Name':'User Name',
   'User Address':'User Address',
   'User Email':'User Email',
   'Product Price:':'Product Price:',
   'Phone Number':'Phone Number',
   'product name:':'product name:',
   'Quantity:':'Quantity:',
   'Total Price:':'Total Price:',
   'Send':'Send',
   '1-Discovers products that do not exist.':'1-Discovers products that do not exist.',
   'About Shqanda':'About Shqanda',
   '2-Excellent quality.':'2-Excellent quality.',
   '3- A place responsible for the products it consumes.':'3- A place responsible for the products it consumes.',
   '4- A place oriented with product quality and history.':'4- A place oriented with product quality and history.',
   '5- A place where you care about the societal environment, the people who make the products, I mean, because the products are excellent.':'5- A place where you care about the societal environment, the people who make the products, I mean, because the products are excellent.',
   'My Cart':'My Cart',
   'price:':'price:',
   'Show Orders':'Show Orders',
   'Show Messages':'Show Messages',
   'Name:':'Name:',
   'Email:':'Email:',
   'Message:':'Message:',
   'Welcome Screen':'Welcome Screen',
   'Login As Admin':'Login As Admin',
   'Login As User':'Login As User',
   'Login As Delivery Boy':'Login As Delivery Boy',
   'Welcome to Shekanda':'Welcome to Shekanda',
   'Sheqanda innovates advanced and distinctive solutions and products':'Sheqanda innovates advanced and distinctive solutions and products',
   'The experience with Sheqanda is governed by quality and a proper diet':'The experience with Sheqanda is governed by quality and a proper diet',
   'Shqanda':'Shqanda',
   'luchra':'luchra',
   'Amount for orders':'Amount for orders',
   'The Italian experience with Luchra':'The Italian experience with Luchra',
   'Try coffee, pizza and chocolate mixed with Italian culture':'Try coffee, pizza and chocolate mixed with Italian culture',
   'delete from cart':'delete from cart',
   'Start Now':'Start Now',
   'Have an account?':'Have an account?',
   'Have not an account?':'Have not an account?',
   "Today's joy lies in products at the door of the house.":"Today's joy lies in products at the door of the house.",
   'Next':'Next',
   'Order':'Order',
   'Checkout':'Checkout',
   'Current Address':'Current Address',
   'Current Phone':'Current Phone',
   'Edit':'Edit',
   'Description':'Description',
   'Amount:':'Amount:',
   'User':'User',
   'Workers in Shekanda':'Workers in Shekanda',
   'Payment Way':'Payment Way'
};
